FROM openjdk:11
ADD target/currency-conversion-service-1.0.0.RELEASE.jar currency-conversion-service-1.0.0.RELEASE.jar
EXPOSE 8100
ENTRYPOINT ["java", "-jar", "currency-conversion-service-1.0.0.RELEASE.jar"] 